## Example 1: Matrix Operations with 2D Arrays

This cell demonstrates creating a 2D array, computing its transpose, and performing matrix multiplication.

In [6]:
import numpy as np

# Creating a 2D array (matrix)
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])

# Transposing the matrix
matrix_T = matrix.T
print("Transposed Matrix:")
print(matrix_T)

Transposed Matrix:
[[1 4]
 [2 5]
 [3 6]]


In [7]:
# Performing matrix multiplication (dot product)
result = np.dot(matrix, matrix_T)
print("\nMatrix multiplied by its transpose:")
print(result)


Matrix multiplied by its transpose:
[[14 32]
 [32 77]]


## Example 2: Data Filtering and Slicing in 2D Arrays

This example shows how to slice and filter rows and columns from a 2D array representing a dataset.

In [8]:
import numpy as np

# Simulate a dataset: rows represent samples and columns represent features
data = np.array([[23, 67, 89],
                 [45, 56, 78],
                 [34, 88, 92],
                 [56, 73, 85]])

In [9]:
# Extracting the first two rows and the last two columns
subset = data[:2, 1:]
print("Subset of the data:")
print(subset)

Subset of the data:
[[67 89]
 [56 78]]


## Example 3: Image Representation and Processing with 2D Arrays

Here we represent a grayscale image as a 2D array and perform a simple inversion of the image.

In [10]:
import numpy as np

# Create a mock 5x5 grayscale image (values range from 0 to 255)
image = np.array([[ 10,  50,  80,  50,  10],
                  [ 20,  60,  90,  60,  20],
                  [ 30,  70, 100,  70,  30],
                  [ 20,  60,  90,  60,  20],
                  [ 10,  50,  80,  50,  10]])

In [11]:
# Simple image inversion
inverted_image = 255 - image
print("Original Image:")
print(image)
print("\nInverted Image:")
print(inverted_image)

Original Image:
[[ 10  50  80  50  10]
 [ 20  60  90  60  20]
 [ 30  70 100  70  30]
 [ 20  60  90  60  20]
 [ 10  50  80  50  10]]

Inverted Image:
[[245 205 175 205 245]
 [235 195 165 195 235]
 [225 185 155 185 225]
 [235 195 165 195 235]
 [245 205 175 205 245]]


## Example 4: Simulating a 3D Environment with 3D Arrays

This cell illustrates how to create a 3D array representing a grid and extract a 2D slice from it.

In [12]:
import numpy as np

# Creating a 3D array to represent a 3x3x3 grid
grid = np.arange(27).reshape(3, 3, 3)
print("3D Grid:")
print(grid)

3D Grid:
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [13]:
# Extracting a 2D slice (e.g., the second "layer" of the grid)
slice_2d = grid[1, :, :]
print("\n2D Slice from the 3D Grid:")
print(slice_2d)


2D Slice from the 3D Grid:
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]


## Example 5: Handling Multi-Channel Data with 3D Arrays

This example shows how to create a 3D array for a RGB image and convert it to grayscale using a weighted sum.

In [14]:
import numpy as np

# Create a 3D array representing a 4x4 RGB image
rgb_image = np.random.randint(0, 256, size=(4, 4, 3))
print("RGB Image:")
print(rgb_image)

RGB Image:
[[[166 224 161]
  [241  75   0]
  [231  27  21]
  [236  12 132]]

 [[130  78 208]
  [ 23  64 202]
  [ 80 152  71]
  [173 161 168]]

 [[200  23  44]
  [208  31 151]
  [157  91 136]
  [ 21 240 206]]

 [[ 60  84  94]
  [ 53 185  77]
  [ 79 118  88]
  [216 135  94]]]


In [15]:
# Convert the image to grayscale using a weighted sum of the RGB channels
grayscale_image = np.dot(rgb_image[...,:3], [0.2989, 0.5870, 0.1140])
print("\nConverted Grayscale Image:")
print(grayscale_image)


Converted Grayscale Image:
[[199.4594 116.0599  87.2889  92.6324]
 [108.355   67.4707 121.23   165.3687]
 [ 78.297   97.5822 115.8483 170.6409]
 [ 77.958  133.2147 102.9111 154.5234]]
